name: NodeJS with Webpack

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

permissions:
    contents: write
    
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]
        node-version: [22.x]
    runs-on: ${{ matrix.os }}
    env:
      targetZip: ${{ github.event.repository.name }}-node-${{ matrix.node-version }}-${{ matrix.os }}${{ github.ref_name }}.zip
    steps:
    
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.4
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10.8'
        
    - run: npm install
    
    - run: npm run-script prebuildify
    
    - working-directory: prebuilds
      run: ls
      
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: "prebuilds"
        filename: "${{ env.targetZip }}"
        
    - name: Release prebuilt
      uses: ncipollo/release-action@v1
      with:
        artifacts: "prebuilds/${{ env.targetZip }}"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
